version: "3.8"
services:
  iot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: server_webiot
    restart: always
    environment:
      DATABASE_HOST: mysql_host
      DATABASE_PORT: 3306
      DATABASE_DATABASE: admin_iotdb
      DATABASE_USER: root
      DATABASE_PASSWORD: root
    ports:
      - 80:80
    volumes:
      - . :/var/www/html
    networks:
      iot_net:
        aliases:
          - iotserver_host

volumes:
  .: {}
networks:
  iot_net:
    name: webiot_net
    driver: bridge
